# Generated by Django 5.0.4 on 2024-05-04 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fatherName', models.CharField(max_length=200)),
                ('dateOfJoining', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProfile.department')),
                ('designition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProfile.designation')),
                ('jobDescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProfile.jobdescription')),
            ],
        ),
    ]
